[versions]
accompanistPermissions = "0.32.0"
activityCompose = "1.9.3"
composeBom = "2024.06.00" # Do not update to keep circle for bars
composeUiVersion = "1.6.8"
coreKtx = "1.13.1"
dataStoreVersion = "1.1.1"
espressoCore = "3.6.1"
fragmentKtx = "1.8.5"
javaxInject = "1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinxSerializationJson = "1.6.3"
ksp = "1.9.0-1.0.13"
lifeCycleVersion = "2.8.7"
material = "1.12.0"
material3 = "1.2.1"
materialIconsVersion = "1.6.8"
media3Common = "1.4.1"
media3Exoplayer = "1.4.1"
media3ExoplayerDash = "1.4.1"
media3Session = "1.4.1"
mediaVersion = "1.7.0"
mp3agic = "0.9.1"
navVersion = "2.7.7"
okhttp = "4.12.0"
roomVersion = "2.6.1"
widgetVersion = "1.1.1"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStoreVersion" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "widgetVersion" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-media = { module = "androidx.media:media", version.ref = "mediaVersion" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3ExoplayerDash" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Common" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "widgetVersion" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "widgetVersion" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifeCycleVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifeCycleVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
mp3agic = { module = "com.mpatric:mp3agic", version.ref = "mp3agic" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
ui = { module = "androidx.compose.ui:ui", version.ref = "composeUiVersion" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeUiVersion" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiVersion" }


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
