[versions]
agp = "8.13.1"
accompanistPermissions = "0.37.3"
activityCompose = "1.12.1"
android-compileSdk = "36" # do not remove even if marked as unused
android-minSdk = "23" # do not remove even if marked as unused
#noinspection OldTargetApi
android-targetSdk = "35" # do not remove even if marked as unused
composeBom = "2025.12.00"
composeUiVersion = "1.10.0"
core = "1.7.0"
coreKtx = "1.17.0"
dataStoreVersion = "1.2.0"
espressoCore = "3.7.0"
fragmentKtx = "1.8.9"
javaxInject = "1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21" # /!\ if update, checks the version of ksp for Android Room
kotlinxSerializationJson = "1.9.0" # Update causes gradle error
ksp = "2.2.21-2.0.4" # 2.2.21 is the kotlin version used in this project: https://github.com/google/ksp/releases/tag/2.2.21-2.0.4
lifeCycleVersion = "2.10.0"
material = "1.13.0"
material3 = "1.4.0"
media3 = "1.8.0"
mediaVersion = "1.7.1"
mockitoCore = "5.21.0"
mockitoKotlin = "6.1.0"
mockk = "1.14.7"
mp3agic = "0.9.1"
navVersion = "2.9.6"
okhttp = "5.3.2"
roomVersion = "2.8.4"
widgetVersion = "1.1.1"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStoreVersion" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "widgetVersion" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-media = { module = "androidx.media:media", version.ref = "mediaVersion" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "widgetVersion" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "widgetVersion" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javaxInject" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifeCycleVersion" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifeCycleVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mp3agic = { module = "com.mpatric:mp3agic", version.ref = "mp3agic" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
ui = { module = "androidx.compose.ui:ui", version.ref = "composeUiVersion" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeUiVersion" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUiVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
